### ISSUE TITLE
A3Q1 - Could not convert string to float

### ISSUE THREAD

**Issue by John-BME** [BME1478H/Winter2020class#88] opened 2020-02-16 20:47 UTC
Hi,
I got the following error. Appreciate any help.

```python
######CODE
def main():
    filename = sys.argv[0]
    experiment_data = np.loadtxt(filename,delimiter=',')
    rate_params =np.array([0.1,1,0.1])
    range_rate = np.arange(float(rate_params[0]), float(rate_params[1]), float(rate_params[2]))
    def squared_error(prediction, data):
        residual = prediction - data
        mse = (residual**2).mean()          
        return mse
    mse = []
    N0 = experiment_data[0]
    t = np.linspace(0, 10, len(experiment_data))
    for r in range_rate:
        prediction = N0*np.exp(r*t)
        mse.append(squared_error(prediction, experiment_data))
        best_fit = range_rate[np.argmin(mse)]
    print('We predict the rate of growth of this bacterial population to be', best_fit)
    
```

```python
if __name__ == '__main__':
 main()
###########Error:
ValueError: could not convert string to float: '"""Entry point for launching an IPython kernel.'
```

**Comment by joelostblom** [comment] 2020-02-16 22:26
In `sys.argv` the first item is the name of the script being run, the second item of `sys.argv` is the first argument you are passing to the script via command line and this is what you want to assign to `filename` in your code.

**Comment by joelostblom** [comment] 2020-02-16 22:31
And just a small tip, you don't need to cast your `rate_params` values as floats since you have already defined them as such when you created the `rate_params` array.

**Comment by John-BME** [comment] 2020-02-16 23:17
Hi, 
Thanks a lot for your prompt response. I edited the code, but I receive the same error for the last part(if name == 'main': main()). I am wondering if please let me know how can I solve it?

**Comment by joelostblom** [comment] 2020-02-16 23:50
I restored your original post and pasted your updated code in this message so that it is easier to follow along in the conversation for someone else with the same issue who is reading this (note that you can surround code with tripple backticks to make it properly indented):
    
```python
def main():
    filename = sys.argv[0]
    experiment_data = np.loadtxt(filename,delimiter=',')
    rate_params =np.array([sys.argv[1],sys.argv[2],sys.argv[3]])
    range_rate = np.arange(rate_params[0], rate_params[1], rate_params[2])
    def squared_error(prediction, data):
        residual = prediction - data
        mse = (residual**2).mean()          
        return mse
    mse = []
    N0 = experiment_data[0]
    t = np.linspace(0, 10, len(experiment_data))
    for r in range_rate:
        prediction = N0*np.exp(r*t)
        mse.append(squared_error(prediction, experiment_data))
        best_fit = range_rate[np.argmin(mse)]
    print('We predict the rate of growth of this bacterial population to be', best_fit)

if __name__ == '__main__':
 main()
```

As I can see it you are still defining the variable `filename` as the scripts name (`sys.argv[0]`), rather than the name of the CSV file that you are trying to read with `np.loadtxt()`. Change this so that you can pass a name of a csv-file on the command line and have it read by `np.loadtxt()`.

**Comment by Ramtin-M** [comment] 2020-02-17 01:51
Hi, Thanks a lot. Sorry about that. I changed it to filename = sys.argv[1] as we define the file name (I think it is the things you asked me). However, I got the following error for the part (if __name__ == '__main__': main()). The error is OSError: -f not found. I am wondering if please help me to solve it.

**Comment by John-BME** [comment] 2020-02-17 01:52
Hi, thank you very much and so sorry about it. I changed it to filename = sys.argv[1] as we define the name in the second argoman. However, I got the following error: OSError: -f not found. I am wondering if please help me to solve it.

**Comment by joelostblom** [comment] 2020-02-17 02:12
No need to apologize! Probably this error is indicating that the first argument you pass to the script is `-f`. If that's not it, could you post the full command you call the script with, and the complete error message with the traceback?

**Comment by John-BME** [comment] 2020-02-17 02:56
The error is currently happened when I just want to run Python script not in the command shell(I just want to make ure my script is correct and then run the sample from the shell).  Am I in the correct way?
#**********
import numpy as np
import array as arr
import sys
def main():
    filename = sys.argv[1]
    experiment_data = np.loadtxt(filename,delimiter=',')
    rate_params =np.array([sys.argv[2],sys.argv[3],sys.argv[4]])
    range_rate = np.arange(rate_params[0], rate_params[1], rate_params[2])
    def squared_error(prediction, data):
        residual = prediction - data
        mse = (residual**2).mean()          
        return mse
    mse = []
    N0 = experiment_data[0]
    t = np.linspace(0, 10, len(experiment_data))
    for r in range_rate:
        prediction = N0*np.exp(r*t)
        mse.append(squared_error(prediction, experiment_data))
        best_fit = range_rate[np.argmin(mse)]
    print('We predict the rate of growth of this bacterial population to be', best_fit)
    
if __name__ == '__main__':
 main()
#******************************************
Error:OSError: -f not found.

**Comment by joelostblom** [comment] 2020-02-17 03:26
Ah ok that explains it. The purpose of `sys.argv` is to get arguments that you pass via the command line when you invoke the script, e.g. `python script_name.py file_name.csv`. It  will not work as intended when you are running it from the notebook, because `sys.argv` will not hold the correct information. You can see this by just typing `sys.argv` in an empty cell, the output will look something like this:

```
['/home/joel/miniconda3/envs/ds/lib/python3.7/site-packages/ipykernel_launcher.py',
 '-f',
 '/home/joel/.local/share/jupyter/runtime/kernel-ba79asd-0-34324jsdfs-j342-00.json']
```

This is how the ipython kernel was invoked when you started your notebook. As you can see, the second argument is `-f`, which is what you are currently trying to use as a filename to read text from and the error you get is telling you that there is no file name `-f` on your system.

Run the script from command line instead and pass it the name of the csv file you want to read. Also change this line `rate_params =np.array([sys.argv[2],sys.argv[3],sys.argv[4]])` back to `rate_params =np.array([0.1,1,0.1])` (unless you want to pass the rate params via the command line, e.g. `python script_name.py file_name.csv 0.1 1 0.1` but for now I recommend changing back to the numbers to keep it simple).

**Comment by John-BME** [comment] 2020-02-17 15:37
Hi, 
Thanks so much, I solved it without running the script. The only thing is that I want to try other parameters, I have to change np.array([0.1,1,0.1]) to np.array([float(sys.argv[2]),float(sys.argv[3]),float(sys.argv[4])]). When I do this, this gets me the TabError: inconsistent use of tabs and spaces in indentation. My indentation is ok, but i don't know how can i solve it?

**Comment by joelostblom** [comment] 2020-02-17 18:45
Hmm, I tried running the code you posted in your previous message and I do not get that error. In general that error occurs when you sometimes use spaces and sometimes use the tab character to indent code and they way to fix it is to go through every indented line and make sure you use spaces everywhere.

If that doesn't work, could you post the chunk of code again, exactly as it is when you are trying to run it (and tell me how you are running it now, still from within the notebook or from the command line?).

**Comment by John-BME** [comment] 2020-02-17 18:56
Hi, 
I am running the following code in the git:
#************Saved Script
import numpy as np
import array as arr
import sys
def main():
    filename = sys.argv[1]
    experiment_data = np.loadtxt(filename,delimiter=',')
    rate_params =np.array([sys.argv[2],sys.argv[3],sys.argv[4]])
![2020-02-17_134818](https://user-images.githubusercontent.com/26355187/74679605-574a9b80-518c-11ea-9201-d8a9f806e0f7.jpg)
![2020-02-17_134818](https://user-images.githubusercontent.com/26355187/74679626-64678a80-518c-11ea-9194-45c045ba6286.jpg)


    range_rate = np.arange(rate_params[0], rate_params[1], rate_params[2])
    def squared_error(prediction, data):
        residual = prediction - data
        mse = (residual**2).mean()          
        return mse
    mse = []
    N0 = experiment_data[0]
    t = np.linspace(0, 10, len(experiment_data))
    for r in range_rate:
        prediction = N0*np.exp(r*t)
        mse.append(squared_error(prediction, experiment_data))
        best_fit = range_rate[np.argmin(mse)]
    print('We predict the rate of growth of this bacterial population to be', best_fit)
if __name__ == '__main__':
 main()
#******************************Called Git Code
$ python model_growth.py bacteria.csv 0 1 0.1
#*****************************************************Errror
TabError: inconsistent use of tabs and spaces in indentation
[model_growth.zip](https://github.com/BME1478H/Winter2020class/files/4215652/model_growth.zip)
Also, I attach the script file.
Thanks alot

**Comment by joelostblom** [comment] 2020-02-17 20:12
I'm on my phone right now, but I don't see any tabs in the code you pasted, what happens if you copy what you pasted here into a script and try to run it?

If that doesn't work, could you attach the script again as a .py file? When I try to open the zip file I get an error saying it's corrupted (might be my phone).

PS don't forget to surround code that you paste on github with triple back quotes so that the indentation shows up.

**Comment by John-BME** [comment] 2020-02-17 20:37
The Github doesn't accept .py!
I am careful about the indention and the attached image shows it!
The problem is for sys.argv. I am not sure how to clear the error.
![2020-02-17_153500](https://user-images.githubusercontent.com/26355187/74685012-4bb2a100-519b-11ea-8731-07c0d656d701.jpg)

**Comment by joelostblom** [comment] 2020-02-18 01:41
Sorry I should have asked you to change the extension from `.py` to `.txt` before uploading, the contents of the file remains the same. But I am my computer now and I was able to open the zip file. I can confirm that you have mixed up tabs and spaces in the indentation. For the following lines of your code, delete all initial whitespaces and make sure to replace them with 4 spaces each:

```python
  # read in the data from the .csv passed to our script
	filename = sys.argv[1]
	experiment_data = np.loadtxt(filename,delimiter=',')
  # store the command-line arguments that represent the start, stop, and step size in the variable rate_params
    #rate_params =np.array([0.1,2,0.1])
	rate_params =np.array([sys.argv[2],sys.argv[3],sys.argv[4]])
  # note: since the parameters that are read by sys.argv are strings, we have to convert them to floats using float(a_string)
```

I just did this with the script you uploaded and I don't run into the mixed tab and spaces error any more.

If you are using atom there you can use [this approach the replace all tabs](https://stackoverflow.com/questions/41848002/how-to-replace-tabs-with-spaces-in-atom). Many editors have a setting to always insert spaces instead of tabs, I am not sure about atom but you can check in the settings menu.

**Comment by John-BME** [comment] 2020-02-18 01:50
Oh! Cool. I tried in Atom and it solved. However, in the Notepad++ it doesn't work! Thanks a lot. 
For ($ python model_growth.py bacteria.csv 0 1 0.1) I got 0.30000000000000004, do you know why this doesn't show me 0.3?

**Comment by joelostblom** [comment] 2020-02-18 02:13
Great that it working!

You have run into a general limitation of representing decimal numbers as binary. You can read more about it here https://docs.python.org/3.7/tutorial/floatingpoint.html. In brief:

> Unfortunately, most decimal fractions cannot be represented exactly as binary fractions. A consequence is that, in general, the decimal floating-point numbers you enter are only approximated by the binary floating-point numbers actually stored in the machine.

A solution that would only affect the output is to format to use less precision, e.g. with `round()`.

**Closed** 2020-02-20 21:36 UTC
