### ISSUE TITLE
A3: predicted and observed data

### ISSUE THREAD

**Issue by moonj94** [BME1478H/Winter2020class#35] opened 2020-01-21 16:56 UTC
For the part about writing a function to predict the growth rate by calculating the mean squared error, which is the predicted and observed data?

Is the predicted data the variable, population_size, and the observed data the variable, population_size_noise?

**Comment by jaelee1204** [comment] 2020-01-21 20:04
I might be wrong but the observed data is the noisy growth rate (more like what an actual recording would look like) and we are trying to find the rate that would yield the smallest MSE. I suppose it should be fairly close to the rate we used to generate population_size

**Comment by moonj94** [comment] 2020-01-21 20:06
That's what I figured. I proceeded with that assumption. Thanks for confirming with your thoughts.

**Comment by RayNele** [comment] 2020-01-22 15:09
Duplicate of #36

**Closed by RayNele** 2020-01-22 15:09 UTC
