### ISSUE TITLE
Unable to find any files

### ISSUE THREAD

**Issue by Mahta-mas** [BME1478H/Winter2020class#6] opened 2020-01-15 23:57 UTC
Hi,

I am trying to access my files and the terminal keeps telling me no such file or directory is found, even though I am certain those files exist. I can list all of the files on my desktop for example but I can't access a specific one. Could you please help?
![Screen Shot 2020-01-15 at 6 43 08 PM](https://user-images.githubusercontent.com/59659485/72481501-bfdadd00-37c8-11ea-8a56-e65cd6152e7e.png)

**Comment by RayNele** [comment] 2020-01-16 00:21
For filenames with spaces you must single quote them, like so `ibmme 1`

**Comment by Mahta-mas** [comment] 2020-01-16 00:26
![Screen Shot 2020-01-15 at 7 26 11 PM](https://user-images.githubusercontent.com/59659485/72482804-ee5ab700-37cc-11ea-952b-2e0a9535c858.png)

I'm still unable to access it.

**Comment by RayNele** [comment] 2020-01-16 00:34
You cd'd into docs, which is not curently where `'ibbme 1'` is located. If you try `ls '~/desktop/ibbme 1` that should solve your problem

**Comment by Mahta-mas** [comment] 2020-01-16 00:42
Thanks, I tried that now. But it's still not listing any items.
![Screen Shot 2020-01-15 at 7 42 13 PM](https://user-images.githubusercontent.com/59659485/72483497-31b62500-37cf-11ea-9edc-5ec1856ed254.png)


> You cd'd into `docs,` which is not curently where `'ibbme 1'` is located. If you try `ls '~/desktop/ibbme 1'` that should solve your problem

**Comment by moonj94** [comment] 2020-01-16 00:45
I think its because there's a space in 'ibbme 1'. Try renaming the  folder to have no spaces and  see if that  works. I had a similar problem earlier. I might be wrong though

**Comment by moonj94** [comment] 2020-01-16 00:48
I don't know about other macs, but for me, when I have to access a folder with a space in  it I have to utilize  the ' \ '.

example:
cd /Users/jaemoon/Documents/Mendeley\ Desktop
(there's a space in 'Mendeley Desktop')

**Comment by RayNele** [comment] 2020-01-16 01:42
I've just double checked it, and the single quote method is working in git bash as intended. 

![image](https://user-images.githubusercontent.com/39201728/72485962-6ded8380-37d7-11ea-8d4b-3955b3ef6ca0.png)

Try @moonj94 's solution, if that doesn't work either, double check that the directory tree exists as you think it does, you may have made changes since the posting of the original thread and my reponse.

**Comment by Mahta-mas** [comment] 2020-01-16 02:15
I got rid of the space and it didn't work either, unfortunately. Could you please elaborate on how to check my directory tree? 
![Screen Shot 2020-01-15 at 9 15 24 PM](https://user-images.githubusercontent.com/59659485/72487485-2ae1df00-37dc-11ea-83dc-4b5ac335de5d.png)

**Comment by RayNele** [comment] 2020-01-16 02:21
try step by step instead of engaging the full path 

`ls`

`cd some-directory`

wherever you want to go next, just make sure it was listed from the previous `ls`

`ls`

and eventually 

`cd 'ibbme 1`

when you see it.

**Comment by RayNele** [comment] 2020-01-16 23:50
Seems like this has solved the problem for you so i will be closing this issue

**Closed by RayNele** 2020-01-16 23:50 UTC
